version: "3.7"
services:
  nginx:
    image: "nginx:alpine"
    restart: always
    hostname: "nginx"
    ports:
    - "${IRACE_EXPOSED_PORT:-8000}:8000"
    volumes:
    - "${IRACE_ROOT:-.}/conf.d:/etc/nginx/conf.d"
    - "${IRACE_ROOT:-.}/static:/irace/static"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 5s
  couchdb:
    image: "couchdb:latest"
    restart: always
    hostname: "couchdb"
    volumes:
    - "${IRACE_DATA:-.}/data:/opt/couchdb/data"
    environment:
      COUCHDB_USER: "${COUCHDB_USER}"
      COUCHDB_PASSWORD: "${COUCHDB_PASSWORD}"
    ports:
    - "5984:5984"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5984/"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s
  admin:
    image: "irace:latest"
    build:
      context: .
      args:
        IRACE_GID: ${IRACE_GID}
        IRACE_UID: ${IRACE_UID}
    restart: always
    hostname: "admin"
    volumes:
    - "${IRACE_ROOT:-.}/html:/irace/html"
    depends_on:
    - nginx
    - couchdb
    ports:
    - "8000"
    environment:
      COUCHDB_HOST: couchdb
      COUCHDB_USER: "${COUCHDB_USER}"
      COUCHDB_PASSWORD: "${COUCHDB_PASSWORD}"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 30s
